- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Check that tags are provided
      fail: 'msg="Please run this playbook with one of the following tags: grafana-install, grafana-reconfigure or grafana-uninstall"'
      when: tags is not defined

# Install latest Grafana Enterprise version
- hosts: grafana
  gather_facts: no
  vars_files:
    - group_vars/grafana
  roles:
    - role: debian-grafana-install
      when: ansible_facts['os_family'] == 'Debian'
  tags: [ never, grafana-install ]

# Reconfigure Grafana Enterprise version
- hosts: grafana
  gather_facts: no
  vars_files:
    - group_vars/grafana
  roles:
    - role: debian-grafana-reconfigure
      when: ansible_facts['os_family'] == 'Debian'
  tags: [ never, grafana-reconfigure ]

# Uninstall Grafana Enterprise version
- hosts: grafana
  gather_facts: no
  vars_files:
    - group_vars/grafana
  roles:
    - role: debian-grafana-uninstall
      when: ansible_facts['os_family'] == 'Debian'
  tags: [ never, grafana-uninstall ]
