############################################################
#
# USAGE:
#   Uninstall Grafana.
#
# PARAMETERS:
#
# PLAYBOOK EXAMPLE:
#   - hosts: grafana
#     gather_facts: yes
#     vars_files:
#       - group_vars/grafana
#     roles:
#       - role: debian-grafana-uninstall
#         when: ansible_facts['os_family'] == 'Debian'
#     tags: [ never, grafana-uninstall ]
#
############################################################

- name: "Stop Grafana services..."
  become: yes
  ansible.builtin.service:
    name: grafana-server
    state: stopped
  ignore_errors: yes

- name: "Uninstall Grafana Enterprise application..."
  become: yes
  ansible.builtin.apt:
    name: "grafana-enterprise"
    state: absent
    purge: true
    update_cache: false
  ignore_errors: no

- name: "Remove Grafana configuration..."
  become: yes
  ansible.builtin.file:
    path: "/etc/grafana"
    state: absent
  ignore_errors: no

- name: "Remove Grafana APT repository..."
  become: yes
  ansible.builtin.apt_repository: 
    repo: "{{ grafana_apt_url }}"
    state: absent
    filename: "{{ grafana_apt_sources_file }}"
  ignore_errors: no

- name: "Remove Grafana GPG key for APT..."
  ansible.builtin.file:
    path: "{{ grafana_apt_key_dst }}"
    state: absent
  ignore_errors: no

- name: "Remove Grafana DB..."
  become: yes
  ansible.builtin.file:
    path: "{{ grafana_data }}"
    state: absent
  ignore_errors: no
